from iqa_models.sda_iqa import SDAIQA
from datasets_in_the_wild import load_dataset
from metrics import PLCC, SRCC
import os
import csv
import torch
from torch.utils.data import DataLoader
import gc
import argparse

# ========== Command-line arguments ==========
parser = argparse.ArgumentParser()
parser.add_argument('--dataset', type=str, default='koniq',
                    choices=['clive', 'koniq', 'livefb', 'spaq'],
                    help='Dataset to evaluate on')
parser.add_argument('--checkpoint', type=str, required=True,
                    help='Path of the trained checkpoint, e.g. checkpoints/koniq_model_plcc_best.pth')
parser.add_argument('--adapter_variant', type=str, default='all',
                    choices=['baseline', 'se_only', 'gate_only', 'scale_only',
                             'se+gate', 'se+scale', 'gate+scale', 'all'],
                    help='Image adapter variant (must match the checkpoint)')
parser.add_argument('--batch_size', type=int, default=8,
                    help='Batch size for evaluation (does not affect the metrics)')
parser.add_argument('--sd_path', type=str, default='runwayml/stable-diffusion-v1-5',
                    help='HuggingFace repo id or local path of the Stable Diffusion v1.5 weights')
parser.add_argument('--class_embedding_path', type=str, default='quality_embeddings.pth',
                    help='Path of the conditional text embeddings generated by gene_text_embedding.py')
parser.add_argument('--train_indices_path', type=str, default=None,
                    help="e.g. 'koniq_train_indices.pth'. Defaults to '{dataset}_train_indices.pth'")
parser.add_argument('--test_indices_path', type=str, default=None,
                    help="e.g. 'koniq_test_indices.pth'. Defaults to '{dataset}_test_indices.pth'")
args = parser.parse_args()

dataset_name = args.dataset
train_indices_path = args.train_indices_path or f'{dataset_name}_train_indices.pth'
test_indices_path = args.test_indices_path or f'{dataset_name}_test_indices.pth'

device = "cuda"

# Load the same train/test split as used in training
_, test_dataset = load_dataset(dataset_name, save_indices=False,
                               load_indices=True,
                               train_indices_path=train_indices_path,
                               test_indices_path=test_indices_path)
test_dataloader = DataLoader(test_dataset, batch_size=args.batch_size, shuffle=False)

# Build the model and load the checkpoint
model = SDAIQA(class_embedding_path=args.class_embedding_path,
               sd_path=args.sd_path,
               adapter_variant=args.adapter_variant)
model.load_state_dict(torch.load(args.checkpoint, map_location='cpu'))
model.to(device)
model.eval()
print(f"Evaluating {args.checkpoint} on {dataset_name} "
      f"({len(test_dataset)} test images, adapter variant: {args.adapter_variant})")

pos = 0
for jpeg_images, gt_scores in test_dataloader:
    pos = pos + 1
    if ((pos % 50) == 0):
        print('batch:' + str(pos) + '/' + str(len(test_dataloader)))

    with torch.no_grad():
        jpeg_images = jpeg_images.to(device)
        bsz = jpeg_images.shape[0]
        gt_scores = gt_scores.view(bsz, 1).to(device)

        test_preds, _ = model(jpeg_images)

        if (pos == 1):
            test_all_preds = test_preds.cpu()
            test_all_gt_scores = gt_scores.cpu()
        else:
            test_all_preds = torch.cat([test_all_preds, test_preds.cpu()], dim=0)
            test_all_gt_scores = torch.cat([test_all_gt_scores, gt_scores.cpu()], dim=0)

        del jpeg_images, test_preds, gt_scores
        gc.collect()
        torch.cuda.empty_cache()

test_plcc = PLCC(test_all_preds, test_all_gt_scores)
test_srcc = SRCC(test_all_preds, test_all_gt_scores)

print("test plcc:" + str(test_plcc.item()) + "  srocc:" + str(test_srcc))

# Save the result for verification
os.makedirs('results', exist_ok=True)
result_file = os.path.join('results', f'result_{dataset_name}.csv')
with open(result_file, 'w', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(['dataset', 'checkpoint', 'adapter_variant', 'SRCC', 'PLCC'])
    writer.writerow([dataset_name, args.checkpoint, args.adapter_variant,
                     float(test_srcc), test_plcc.item()])
print(f"Result saved to {result_file}")